DROP TABLE IF EXISTS Commentaires;
DROP TABLE IF EXISTS Notes;
DROP TABLE IF EXISTS PlaylistChansons;
DROP TABLE IF EXISTS Playlists;
DROP TABLE IF EXISTS Chansons;
DROP TABLE IF EXISTS Albums;
DROP TABLE IF EXISTS Artistes;
DROP TABLE IF EXISTS Utilisateurs;
